# baseURL = "http://example.org/"
languageCode = "en-us"
title = "Beth Aitman"
theme = ["my-theme-edits", "book"]

[params]
# Configure the date format used in git information and  blog posts
BookDateFormat = 'Jan 2006'
