# baseURL = "http://example.org/"
languageCode = "en-us"
title = "Beth Aitman"
theme = ["hugo-book"]
summaryLength = 10

[params]
# Disable search
BookSearch = false
# Configure the date format used in git information and  blog posts
BookDateFormat = 'Jan 2006'

[menu]
  [[menu.after]]
    name = 'CV'
    pageRef = '/cv'
    weight = 10
  [[menu.after]]
    name = 'Speaking'
    pageRef = '/talks'
    weight = 20
  [[menu.after]]
    name = 'Writing'
    pageRef = '/posts'
    weight = 30